import { Poppins } from "next/font/google";
import Header from "./components/Header";

import 'swiper/scss';
import 'swiper/scss/navigation';
import "./styles/main.scss";
import Footer from "./components/Footer";



const poppins = Poppins({
	weight: ["400", "500", "700", "900"],
	subsets: ["latin"],
});

export const metadata = {
	title: "...",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {



	return (
		<html lang="en">
			<body className={poppins.className}>
				<Header />
				
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
